library(datasets)
hist(airquality$Ozone)
with(airquality, plot(Wind,Ozone))
airquality <- transform(airquality, Month = factor(Month))
boxplot(Ozone ~ Month, airquality, xlab = "Month", ylab = "Ozone (ppb)")

x <- rnorm(100)
hist(x)
rug(x)
y <- rnorm(100)
plot(x,y, pch=18)
z <- rnorm(100)
plot(x,z)
plot(x,y)
par( mar = c(2,2,2,2))
plot(x,y)
par(mar = c(4,4,2,2))
plot(x,y)
plot(x,y, pch = 17)
plot(x,y,pch=20)
title("My scatterplot")
text(-2,2,"Label")
legend("topleft",legend = "Data", pch = 20)
fit <- lm(y ~ x)
abline(fit, lwd = 3, col = "magenta")
plot(x,y, xlab="Weight", ylab= "Height", main = "Scatterplot", pch = 20)
legend("topright", legend="data", pch = 20)
z <- rpois(100,2)
par(mfrow = c(1,2))
plot(x,y,pch=20)
plot(x,z,pch=19)
par("mar")
par(mar= c(4,4,2,2))
plot(x,y,pch=20)
plot(x,z,pch=19)
par(mfrow=c(2,2))
plot(x,y)
plot(x,z)
plot(z,x)
plot(y,x)
x <- rnorm(100)
y<-x + rnorm(100)
g <- gl(2,40,labels = c("Male","Female"))
str(g)
plot(x,y)
par(mfrow=c(1,1))
plot(x,y)
plot(x,y,type="n")
points(x[g=="Male"], y[g=="Male"],col = "blue")
points(x[g=="Female"], y[g=="Female"],col = "magenta", pch = 18)
